apiVersion: v1
kind: ConfigMap
metadata:
  name: flyway-sql-config
  namespace: db-migration-demo
data:
  V1__first_script.sql: |
    CREATE TABLE users (
      id SERIAL PRIMARY KEY,
      name VARCHAR(100)
    );