apiVersion: v1
data:
  V1__first_script.sql: |-
    CREATE TABLE users (
          id SERIAL PRIMARY KEY,
          name VARCHAR(100)
    );
  V2__add_products_table.sql: |-
    CREATE TABLE products (
          id SERIAL PRIMARY KEY,
          product_name VARCHAR(100)
    );
  V3__add_orders_table.sql: |-
    CREATE TABLE orders (
          id SERIAL PRIMARY KEY,
          order_name VARCHAR(100)
        );
  V4__add_payments_table.sql: |-
    CREATE TABLE payments (
       id SERIAL PRIMARY KEY,
       amount DECIMAL(10,2),
       payment_date TIMESTAMP DEFAULT NOW()
    );
kind: ConfigMap
metadata:
  name: flyway-sql-config
