apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-migration
  namespace: db-migration-demo
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: flyway
          image: flyway/flyway:10
          args:
            [
              "-url=jdbc:postgresql://postgres:5432/testdb",
              "-user=testuser",
              "-password=testpassword",
              "migrate"
            ]
          volumeMounts:
            - name: flyway-sql
              mountPath: /flyway/sql
      volumes:
        - name: flyway-sql
          configMap:
            name: flyway-sql
