apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: db-migration-demo
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: testdb
            - name: POSTGRES_USER
              value: testuser
            - name: POSTGRES_PASSWORD
              value: testpassword
          # No volumeMounts — ephemeral storage will be used
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: db-migration-demo
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
