name: Sync ArgoCD App on SQL Change

on:
  push:
    paths:
      - 'flyway/sql/**'   # Only trigger when SQL files change
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync ArgoCD Application
        run: |
          curl -k -X POST \
            -H "Content-Type: application/json" \
            -u ${{ secrets.ARGOCD_USERNAME }}:${{ secrets.ARGOCD_PASSWORD }} \
            https://argocd-server/api/v1/applications/flyway-migration-demo/sync
